# Builder layer
FROM golang:1.24 AS build

WORKDIR /go/src/fsdweb

# Download dependencies
COPY go.mod go.sum ./

RUN go mod download

# Build
COPY . .

RUN cd web && CGO_ENABLED=0 go build -ldflags "-s -w" -o /go/bin/fsdweb

# Runner layer
FROM alpine:latest

RUN addgroup -g 2001 nonroot && \
    adduser -u 2001 -G nonroot -D nonroot && \
    mkdir /db && chown -R nonroot:nonroot /db

COPY --from=build --chown=nonroot:nonroot /go/bin/fsdweb /

USER 2001:2001

CMD ["/fsdweb"]
