services:
  fsd:
    image: ghcr.io/renorris/openfsd-fsd:latest
    restart: unless-stopped
    ports:
      - 6809:6809/tcp
    environment:
      DATABASE_SOURCE_NAME: /db/openfsd.db?_pragma=busy_timeout(5000)&_pragma=journal_mode(WAL)
      DATABASE_AUTO_MIGRATE: true
    volumes:
      - db:/db

  web:
    image: ghcr.io/renorris/openfsd-web:latest
    restart: unless-stopped
    ports:
      - 8000:8000/tcp
    environment:
      DATABASE_SOURCE_NAME: /db/openfsd.db?_pragma=busy_timeout(5000)&_pragma=journal_mode(WAL)
      FSD_HTTP_SERVICE_ADDRESS: http://fsd:13618
    volumes:
      - db:/db

volumes:
  db:
